#!/usr/bin/env bash
#
# Regenerate the example reports and check the committed copies match.
#
# The examples are committed as documentation and as a format reference. They
# are generated files, so they go stale the moment the analyzer changes - and a
# stale example is worse than no example, because it documents behaviour the
# tool no longer has. This was written after exactly that happened.
#
# A report whose source bundle is gone cannot be regenerated, and is skipped
# with a note rather than silently passing.
#
#   scripts/tests/check-examples-current.sh

set -u -o pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SCRIPTS="$(dirname "$HERE")"
REPO="$(dirname "$SCRIPTS")"
ANALYZE="$SCRIPTS/analyze-astraeus-bundle.py"
EXAMPLES="$SCRIPTS/examples"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/astraeus-examples.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

failures=0
checked=0
skipped=0

# compare <example file> <source bundle> [extra analyzer args...]
compare() {
    local example="$1" source="$2"; shift 2
    local name
    name="$(basename "$example")"

    if [ ! -e "$source" ]; then
        printf 'SKIP %s: source bundle %s is not present (it is under .tmp/ and is usually gone)\n' \
            "$name" "$source"
        skipped=$((skipped + 1))
        return 0
    fi

    if ! python3 "$ANALYZE" "$source" "$@" --out "$TMP/$name" >/dev/null 2>&1; then
        printf 'FAIL %s: the analyzer could not read %s\n' "$name" "$source"
        failures=$((failures + 1))
        return 0
    fi

    checked=$((checked + 1))
    if diff -q "$example" "$TMP/$name" >/dev/null 2>&1; then
        printf 'ok   %s\n' "$name"
    else
        printf 'FAIL %s: the committed example is not what the analyzer produces now\n' "$name"
        diff "$example" "$TMP/$name" | head -20
        failures=$((failures + 1))
    fi
}

# The real bundles live under .tmp/ and are frequently cleaned; when they are
# missing the check says so rather than reporting a pass it did not earn.
compare "$EXAMPLES/report-binary-process.md" \
    "$REPO/.tmp/diag-final3/astraeus-diag-omarchy-20261009T205909Z.tar.gz"

compare "$EXAMPLES/report-amd-vaapi-live-session.md" \
    "$REPO/.tmp/report-demo/astraeus-diag-omarchy-20261009T203518Z.tar.gz"

# The synthetic example's source is a loose directory, which is cheaper to keep
# than a tarball and is regenerated by make-fixture-bundle.py.
compare "$EXAMPLES/report-intel-nvidia-example.md" \
    "$REPO/.tmp/astfix/t2" --label "astraeus-diag-intel-nvidia-EXAMPLE.tar.gz"

printf '\n%d checked, %d skipped, %d failed\n' "$checked" "$skipped" "$failures"
if [ "$skipped" -gt 0 ] && [ "$checked" -eq 0 ]; then
    printf 'note: nothing was actually verified - rebuild the source bundles first\n'
fi
exit $((failures > 0 ? 1 : 0))
